# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
      paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
        
jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-latest]
        swift: ["5.6", "5.7"]
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      if: ${{ startsWith(matrix.swift, '5.6') }}
      with:
        xcode-version: '13.4.1'
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
