# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
      paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.5", "5.6", "5.7", "5.8"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v3
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
